require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExitsController do

  # This should return the minimal set of attributes required to create a valid
  # Exit. As you add validations to Exit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "location_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exits as @exits" do
      exit = Exit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exits).should eq([exit])
    end
  end

  describe "GET show" do
    it "assigns the requested exit as @exit" do
      exit = Exit.create! valid_attributes
      get :show, {:id => exit.to_param}, valid_session
      assigns(:exit).should eq(exit)
    end
  end

  describe "GET new" do
    it "assigns a new exit as @exit" do
      get :new, {}, valid_session
      assigns(:exit).should be_a_new(Exit)
    end
  end

  describe "GET edit" do
    it "assigns the requested exit as @exit" do
      exit = Exit.create! valid_attributes
      get :edit, {:id => exit.to_param}, valid_session
      assigns(:exit).should eq(exit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Exit" do
        expect {
          post :create, {:exit => valid_attributes}, valid_session
        }.to change(Exit, :count).by(1)
      end

      it "assigns a newly created exit as @exit" do
        post :create, {:exit => valid_attributes}, valid_session
        assigns(:exit).should be_a(Exit)
        assigns(:exit).should be_persisted
      end

      it "redirects to the created exit" do
        post :create, {:exit => valid_attributes}, valid_session
        response.should redirect_to(Exit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exit as @exit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Exit.any_instance.stub(:save).and_return(false)
        post :create, {:exit => { "location_id" => "invalid value" }}, valid_session
        assigns(:exit).should be_a_new(Exit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Exit.any_instance.stub(:save).and_return(false)
        post :create, {:exit => { "location_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exit" do
        exit = Exit.create! valid_attributes
        # Assuming there are no other exits in the database, this
        # specifies that the Exit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Exit.any_instance.should_receive(:update).with({ "location_id" => "1" })
        put :update, {:id => exit.to_param, :exit => { "location_id" => "1" }}, valid_session
      end

      it "assigns the requested exit as @exit" do
        exit = Exit.create! valid_attributes
        put :update, {:id => exit.to_param, :exit => valid_attributes}, valid_session
        assigns(:exit).should eq(exit)
      end

      it "redirects to the exit" do
        exit = Exit.create! valid_attributes
        put :update, {:id => exit.to_param, :exit => valid_attributes}, valid_session
        response.should redirect_to(exit)
      end
    end

    describe "with invalid params" do
      it "assigns the exit as @exit" do
        exit = Exit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Exit.any_instance.stub(:save).and_return(false)
        put :update, {:id => exit.to_param, :exit => { "location_id" => "invalid value" }}, valid_session
        assigns(:exit).should eq(exit)
      end

      it "re-renders the 'edit' template" do
        exit = Exit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Exit.any_instance.stub(:save).and_return(false)
        put :update, {:id => exit.to_param, :exit => { "location_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exit" do
      exit = Exit.create! valid_attributes
      expect {
        delete :destroy, {:id => exit.to_param}, valid_session
      }.to change(Exit, :count).by(-1)
    end

    it "redirects to the exits list" do
      exit = Exit.create! valid_attributes
      delete :destroy, {:id => exit.to_param}, valid_session
      response.should redirect_to(exits_url)
    end
  end

end
